fix

diff --git a/.github/workflows/deploy_debug.yml b/.github/workflows/deploy_debug.yml
--- a/.github/workflows/deploy_debug.yml
+++ b/.github/workflows/deploy_debug.yml
@@ -32,6 +32,9 @@ jobs:
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v4.1.0
 
+      - name: Debug - Check Gradle File
+        run: ls -l app/build.gradle.kts || echo "File not found!"
+
       - name: Increment Version Code
         run: |
           # Find the current versionCode in build.gradle.kts
